// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8J59omZo_TtHM4RjBFi7bGdru0klkJs',
    appId: '1:73728837802:web:2a9760f777eae4b0d368d3',
    messagingSenderId: '73728837802',
    projectId: 'activity-db71e',
    authDomain: 'activity-db71e.firebaseapp.com',
    storageBucket: 'activity-db71e.firebasestorage.app',
  );
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8J59omZo_TtHM4RjBFi7bGdru0klkJs',
    appId: '1:73728837802:web:2a9760f777eae4b0d368d3',
    messagingSenderId: '73728837802',
    projectId: 'activity-db71e',
    authDomain: 'activity-db71e.firebaseapp.com',
    storageBucket: 'activity-db71e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8J59omZo_TtHM4RjBFi7bGdru0klkJs',
    appId: '1:73728837802:web:2a9760f777eae4b0d368d3',
    messagingSenderId: '73728837802',
    projectId: 'activity-db71e',
    authDomain: 'activity-db71e.firebaseapp.com',
    storageBucket: 'activity-db71e.firebasestorage.app',
  );
}
